### ISSUE TITLE
Import failed - Invalid tag "/zabbix_export": unexpected tag "groups"

### ISSUE THREAD

**Issue by leonroy** [kko/unifi-zabbix-snmpv3#3]
First thanks for the great Zabbix Templates. The Synology one worked perfectly👌

On trying to import the Unifi template however I see the below error:
```
Details Import failed
Invalid tag "/zabbix_export": unexpected tag "groups".
```

![image](https://user-images.githubusercontent.com/325602/80317285-d3033d00-87fa-11ea-8b50-549e8adac286.png)

Looking at the Synology and Unifi templates, the `groups` tags seem identical and the XML itself validates fine with zero errors.

I'm using Zabbix 4.4.7.

Do you have any idea what the problem might be?

**Comment by leonroy** [comment]
I assume the `version` number in the XML file is the Zabbix version?

It's set to `1.0` in file `Template_UBQT_UNIFI_SNMP_V3_HN_1.xml` which must be an error since I'm assuming you're not using Zabbix 1.0 😏

Setting it to `4.0` allowed the Template to import but probably best if you set it to the version of the Zabbix server you expored the file from.

**Comment by kko** [comment]
Your are right. I did a mistake.
