### ISSUE TITLE
Error importing 

### ISSUE THREAD

**Issue by adutra22** [kko/unifi-zabbix-snmpv3#8]
Trying to import into Zabbix 4.4 and get the following errors:
When trying to import file "Template_UBQT_UNIFI_SNMP_V3_HN_1.xml"
Error:  Cannot read XML: (41) Specification mandate value for attribute data-pjax-transient [Line: 51 | Column: 69].

When trying to import file "Template_UBQT_UNIFI_SWITCH_SNMP_V3.xml"
Error:  Cannot read XML: (41) Specification mandate value for attribute data-pjax-transient [Line: 51 | Column: 69].

Perhaps I'm missing some step or configuration?

thanks!

**Comment by kko** [comment]
think i need to check that. no idea yet

**Comment by kko** [comment]
Work with 6.0
